/**
 * Single translation unit that compiles the header-only Boost.JSON library.
 *
 * <boost/json/src.hpp> emits the definitions of the whole library, so it must
 * be included in exactly one TU. Every other file uses <boost/json.hpp> (or a
 * more specific declaration header) instead; otherwise the linker reports
 * duplicate symbols.
 */
#include <boost/version.hpp>

#if BOOST_VERSION / 100 % 100 >= 80

// To silence warnings generated by the Boost json library
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wcovered-switch-default"
#pragma GCC diagnostic ignored "-Wnon-virtual-dtor"
#pragma GCC diagnostic ignored "-Wimplicit-fallthrough"

#include <boost/json/src.hpp>

#pragma GCC diagnostic pop

#endif
