#include "write_json_llm.hh"
#include <boost/version.hpp>

#if BOOST_VERSION / 100 % 100 < 80
#include "llvm/Support/raw_ostream.h"
namespace clam {
namespace json {
class json_llm_report_impl {
public:
  void write(cfg_ref_t, const AnalysisParams &, const abs_dom_map_t &,
             const abs_dom_map_t &, const checks_db_t &,
             const json_llm_report::voi_map_t &) {}
  std::string generate() {
    llvm::errs()
        << "Warning: too old version of boost. It needs >= 1.80 for json support\n";
    return "";
  }
};
} // end namespace json
} // end namespace clam

#else
/** Real implementation starts here **/

// To silence warnings generated by the Boost json library
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wcovered-switch-default"
#pragma GCC diagnostic ignored "-Wnon-virtual-dtor"
#pragma GCC diagnostic ignored "-Wimplicit-fallthrough"

#include <boost/json/src.hpp>
#include <clam/Support/Debug.hh>
#include <crab/checkers/base_property.hpp>

namespace clam {
namespace json {

// crab statement kinds we treat as assertions
using assert_t = typename basic_block_t::assert_t;
using assert_ref_t = typename basic_block_t::assert_ref_t;
using bool_assert_t = typename basic_block_t::bool_assert_t;

class json_llm_report_impl {
  // function name -> {declaration, assertions:[...]}
  boost::json::object m_functions;
  std::string m_source;

  // Render the assertion's constraint exactly as the crabir printer does, so
  // the native output matches the --ocrab converter.
  static std::string constraint_str(const statement_t &s) {
    crab::crab_string_os os;
    if (s.is_assert()) {
      os << static_cast<const assert_t *>(&s)->constraint();
    } else if (s.is_ref_assert()) {
      os << static_cast<const assert_ref_t *>(&s)->constraint();
    } else if (s.is_bool_assert()) {
      os << static_cast<const bool_assert_t *>(&s)->cond();
    }
    return os.str();
  }

  static std::string kind_str(const statement_t &s) {
    if (s.is_ref_assert())
      return "ref_assert";
    if (s.is_bool_assert())
      return "bool_assert";
    return "assert";
  }

  // Invariant that holds at the entry of BB, with ghost variables filtered out
  // (same procedure as write_json.cc). Returns false if no invariant is known.
  static bool block_invariant_str(const llvm::BasicBlock *BB,
                                  const AnalysisParams &params,
                                  const abs_dom_map_t &invariants,
                                  std::string &out) {
    auto it = invariants.find(BB);
    if (it == invariants.end()) {
      return false;
    }
    clam_abstract_domain absVal(it->second);
    if (!params.keep_shadow_vars) {
      auto csts = absVal.to_linear_constraint_system();
      std::vector<var_t> ghosts;
      for (auto const &cst : csts) {
        for (auto v : cst.variables()) {
          if (v.name().get() == boost::none) {
            ghosts.push_back(v);
          }
        }
      }
      absVal.forget(ghosts);
    }
    crab::crab_string_os os;
    absVal.to_linear_constraint_system().write(os);
    out = os.str();
    return true;
  }

public:
  json_llm_report_impl() {}
  ~json_llm_report_impl() = default;

  void write(cfg_ref_t cfg, const AnalysisParams &params,
             const abs_dom_map_t &invariants,
             const abs_dom_map_t &post_invariants, const checks_db_t &checks,
             const json_llm_report::voi_map_t &voi) {
    if (!cfg.has_func_decl()) {
      CLAM_ERROR("write_json_llm requires a cfg to have a name");
    }
    std::string fname = cfg.get_func_decl().get_func_name();

    crab::crab_string_os decl_os;
    decl_os << cfg.get_func_decl();

    boost::json::array assertions;

    for (auto bbl :
         llvm::make_range(cfg.label_begin(), cfg.label_end())) {
      const llvm::BasicBlock *BB = bbl.get_basic_block();
      if (!BB) {
        continue;
      }
      std::string block = bbl.get_name();

      std::string inv_str;
      bool has_inv = block_invariant_str(BB, params, invariants, inv_str);
      std::string inv_exit_str;
      bool has_inv_exit =
          block_invariant_str(BB, params, post_invariants, inv_exit_str);

      const basic_block_t &bb = cfg.get_node(bbl);
      for (auto const &s : bb) {
        if (!(s.is_assert() || s.is_ref_assert() || s.is_bool_assert())) {
          continue;
        }
        const crab::cfg::debug_info &di = s.get_debug_info();

        // classify OK / FAIL exactly as the crabir printer does
        unsigned safe = 0, warning = 0, error = 0;
        bool has_checks = checks.has_checks(di);
        if (has_checks) {
          for (auto k : checks.get_checks(di)) {
            switch (k) {
            case crab::checker::check_kind::CRAB_SAFE:
            case crab::checker::check_kind::CRAB_UNREACH:
              safe++;
              break;
            case crab::checker::check_kind::CRAB_ERR:
              error++;
              break;
            default:
              warning++;
              break;
            }
          }
        }
        std::string result = "UNKNOWN";
        if (has_checks) {
          result = (error == 0 && warning == 0) ? "OK" : "FAIL";
        }

        boost::json::object a;
        a["id"] = di.get_id();
        a["file"] = di.get_file();
        a["line"] = di.get_line();
        a["col"] = di.get_column();
        a["kind"] = kind_str(s);
        a["constraint"] = constraint_str(s);
        a["result"] = result;
        boost::json::object counts;
        counts["safe"] = safe;
        counts["error"] = error;
        counts["warning"] = warning;
        a["counts"] = counts;
        a["block"] = block;
        if (has_inv) {
          a["invariant"] = inv_str;
        } else {
          a["invariant"] = nullptr;
        }
        if (has_inv_exit) {
          a["invariant_exit"] = inv_exit_str;
        } else {
          a["invariant_exit"] = nullptr;
        }
        boost::json::array voi_arr;
        auto vit = voi.find({block, di.get_id()});
        if (vit != voi.end()) {
          for (auto const &v : vit->second) {
            voi_arr.push_back(boost::json::value(v));
          }
        }
        a["variables_of_influence"] = voi_arr;
        a["invariant_sliced"] = nullptr; // filled by crab_llm_json.enrich
        assertions.push_back(std::move(a));
      }
    }

    boost::json::object body;
    body["declaration"] = decl_os.str();
    body["assertions"] = std::move(assertions);
    m_functions[fname] = std::move(body);
  }

  std::string generate() {
    boost::json::object report;
    report["schema_version"] = "1.0";
    report["generator"] = "clam --ojson-llm";
    report["source"] = nullptr;
    report["functions"] = m_functions;
    return boost::json::serialize(report);
  }
};

} // end namespace json
} // end namespace clam
#pragma GCC diagnostic pop
#endif

namespace clam {
namespace json {

json_llm_report::json_llm_report()
    : m_pimpl(std::make_unique<json_llm_report_impl>()) {}

json_llm_report::~json_llm_report() = default;

void json_llm_report::write(cfg_ref_t cfg, const AnalysisParams &params,
                            const abs_dom_map_t &invariants,
                            const abs_dom_map_t &post_invariants,
                            const checks_db_t &checks, const voi_map_t &voi) {
  m_pimpl->write(cfg, params, invariants, post_invariants, checks, voi);
}

std::string json_llm_report::generate() { return m_pimpl->generate(); }

} // end namespace json
} // end namespace clam
