# Dockerfile for Clam binary
# produces package in /clam/build
#
# Arguments:
#  - LLVM_VERSION: major LLVM release to build against (e.g. 16, 17, 18). Drives
#    the base image, the clang/clang++/llvm-dis binaries and the tool symlinks.
#  - BUILDPACK_IMAGE: buildpack-deps image repo. LLVM 15+ base images are
#    published on GitHub Container Registry; the older Docker Hub
#    seahorn/buildpack-deps-seahorn only goes up to jammy-llvm14.
#  - BASE_IMAGE: buildpack tag (defaults to jammy-llvm${LLVM_VERSION})
#  - BUILD_TYPE: Debug, RelWithDebInfo, Coverage
#  - CRAB_USE_LDD: ON builds the Ldd library, which is what provides the Boxes
#    domain. The SVCOMP suites (ssh-simplified, ntdrivers-simplified) are only
#    generated by tests/CMakeLists.txt when this is ON, so they are also only
#    run when it is ON.
ARG LLVM_VERSION=17
ARG BUILDPACK_IMAGE=ghcr.io/seahorn/buildpack-deps-seahorn
ARG BASE_IMAGE=jammy-llvm${LLVM_VERSION}
FROM ${BUILDPACK_IMAGE}:${BASE_IMAGE}

# ARGs declared before FROM are only visible to FROM; re-declare to use below.
ARG LLVM_VERSION

# libc6-dev-i386: needed to run clang with -m32.
# python3-pip: to install OutputCheck below (the lit tests pipe into it).
RUN apt-get install -yqq libc6-dev-i386 python3-pip

# Assume that docker-build is ran in the top-level Clam directory
COPY . /clam
# Re-create the build directory that might have been present in the source tree
RUN rm -rf /clam/build /clam/debug /clam/release && \
  mkdir /clam/build && \
# Remove any third-party dependencies that build process clones
  rm -rf /clam/crab /clam/sea-dsa /clam/llvm-seahorn
WORKDIR /clam/build

ARG BUILD_TYPE=Release
ARG CRAB_USE_LDD=ON

# Build configuration.
# ldd, like apron, is an ExternalProject that crab marks EXCLUDE_FROM_ALL, so
# it has to be built by name; the cmake .. that follows re-runs find_package so
# the just-installed library is picked up. Its target only exists when
# CRAB_USE_LDD is ON, hence the guard.
#
# ldd MUST be built before apron. crab's CMakeLists looks for its optional
# dependencies in a fixed order -- ldd, then pplite, then apron, then elina --
# and return()s at the first one it cannot find, so a configure pass resolves
# exactly one of them and later blocks are not reached at all. Since apron is
# only findable through the APRON_ROOT that its own block sets, building apron
# while ldd is still unresolved leaves APRON_ROOT empty; crab then returns
# early forever, never exports its include directories, and clam fails to
# compile with "'crab/support/debug.hpp' file not found".
#
# Each step below is its own RUN so that a failure in a later one does not throw
# away the earlier ones: everything up to the failing step stays in the build
# cache and is reused on the next build. Keeping them in a single RUN means one
# layer, so a failure anywhere discards the whole thing including apron.
#
# apron and ldd are built by recursive make, which crab invokes without -j.
# MAKEFLAGS reaches those sub-makes through the environment and is the only way
# to parallelize them without patching crab, which this image re-clones anyway.
RUN cmake .. -GNinja \
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
          -DCMAKE_INSTALL_PREFIX=run \
          -DCMAKE_CXX_COMPILER=clang++-${LLVM_VERSION} \
          -DCMAKE_C_COMPILER=clang-${LLVM_VERSION} \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
          -DCRAB_USE_APRON=ON \
          -DCRAB_USE_LDD=${CRAB_USE_LDD}

RUN cmake --build . --target extra && cmake ..

RUN cmake --build . --target crab && cmake ..

RUN if [ "${CRAB_USE_LDD}" = "ON" ]; then \
      MAKEFLAGS=-j$(nproc) cmake --build . --target ldd && cmake .. ; \
    fi

RUN MAKEFLAGS=-j$(nproc) cmake --build . --target apron && cmake ..

RUN cmake --build . --target install

RUN ln -s /usr/bin/clang-${LLVM_VERSION} /usr/bin/clang
RUN ln -s /usr/bin/llvm-dis-${LLVM_VERSION} /usr/bin/llvm-dis
ENV PATH "/usr/bin:$PATH"
ENV PATH "/clam/build/run/bin:$PATH"

# lit is provided by the base image, but OutputCheck (which the lit RUN
# directives pipe into) is not; install it.
RUN pip3 install --no-cache-dir OutputCheck

# run tests
RUN cmake --build . --target test-simple
RUN cmake --build . --target test-readme
RUN cmake --build . --target test-inter
RUN cmake --build . --target test-array-adapt
RUN cmake --build . --target test-mem
RUN cmake --build . --target test-devirt
RUN cmake --build . --target test-opt

# The SVCOMP suites need the Boxes domain, so their targets only exist when
# CRAB_USE_LDD is ON. Skip them otherwise rather than fail on a missing target.
RUN if [ "${CRAB_USE_LDD}" = "ON" ]; then \
      cmake --build . --target test-ssh-simplified && \
      cmake --build . --target test-ntdrivers-simplified ; \
    else \
      echo "CRAB_USE_LDD=${CRAB_USE_LDD}: skipping the SVCOMP suites" ; \
    fi

WORKDIR /clam
