if (NOT IKOS_FOUND)
  find_path(IKOS_INCLUDE_DIR NAMES Cfg.hpp PATHS ${IKOS_ROOT}/include/ikos_cfg NO_DEFAULT_PATH)
  get_filename_component(IKOS_INCLUDE_DIR ${IKOS_INCLUDE_DIR} DIRECTORY)
  include (FindPackageHandleStandardArgs)
  find_package_handle_standard_args(IKOS REQUIRED_VARS IKOS_INCLUDE_DIR) 
  mark_as_advanced(IKOS_SEARCH_PATH IKOS_INCLUDE_DIR)
endif()